### ISSUE TITLE
pubsub’s old API not work on wxPython >= 2.9

### ISSUE THREAD

**Issue by jeanslack** [jeanslack/Videomass#1]
This issue is localized in os.processing.py module and regards wxPython 3.0 in my installation, while on wxPython versions <= 2.8 still works 

OUTPUT:
ImportError: Cannot import name Publisher

Publisher work with wxPython <= 2.8 but don't work in wxPython 3.0

I'm resolve this issue following this site: http://www.blog.pythonlibrary.org/2013/09/04/wxpython-how-to-update-a-progress-bar-from-a-thread/

So, the row import become:
from wx.lib.pubsub import Publisher  # this work in wxPython <=2.8
from wx.lib.pubsub import pub # this work in wxPython 3.0

..and :
wx.CallAfter(Publisher().sendMessage, "update", "")  # this work in wxPython <= 2.8
to:
wx.CallAfter(pub.subscribe(sendMessage, "update")) # this work in wxPython 3.0

..and from:
Publisher().subscribe(self.updateProgress, "update")  # this work in wxPython <=2.8
to:
pub.subscribe(self.updateProgress, "update") # this work in wxPython 3.0

..but I am looking for a portable solution that work in wxPython 2.8 and wxPython 3.0, any ideas ?
